name: notification_kosmos
description: A new Flutter package project.
version: 0.0.1
homepage: none
publish_to: none
environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^1.0.4
  cloud_firestore: ^3.4.7
  firebase_auth: ^3.8.0
  easy_localization: null
  core_kosmos:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  ui_kosmos_v4:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  flutter_svg: ^1.1.5
  timeago_flutter: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  freezed: ^2.0.3
  auto_route_generator: ^4.2.0
  json_serializable: ^6.2.0
flutter:
  assets:
  - assets/
